### ISSUE TITLE
Support sirepo.jupyterhub.uri and jupyterhub.sirepo_uri

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#124]
We need to pass configuration to both servers so just have two parameters with reasonable defaults.

Possibly add a check in component.jupyterhub_proxy and component.sirepo to ask if jupyterhub.sirepo_uri is set or not, appropriately.

**Comment by robnagler** [comment]
@e-carlin do you remember why I created this?

**Comment by e-carlin** [comment]
I don't.

**Comment by robnagler** [comment]
I think we don't need this anymore.
