### ISSUE TITLE
sirepo_uri for sirepo_jupyterhub

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#182]
cc: @rorour (can't figure out how to get your name to appear in the list of assignees...)

@robnagler can you provide some guidance on how to get the sirepo uri so it can be provided to sirepo_jupyterhub for https://github.com/radiasoft/sirepo/commit/78abea726afdd196a064a36d87dacf5c52bc0b0a ?

I think it might be from the sirepo.vhost but not positive. Also, can we just assume https? [Looks like it](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo_job_supervisor.py#L99) but I want to confirm

**Comment by robnagler** [comment]
> cc: @rorour (can't figure out how to get your name to appear in the list of assignees...)

radiasoft/software didn't have access, just devops.

> @robnagler can you provide some guidance on how to get the sirepo uri so it can be provided to sirepo_jupyterhub for https://github.com/radiasoft/sirepo/commit/78abea726afdd196a064a36d87dacf5c52bc0b0a ?

* Add to [conf.py.jinja](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/package_data/sirepo_jupyterhub/conf.py.jinja)
* Add code [like this](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L111). It could be constructed from the nginx.vhost and assume https.
* Add a line [like this one](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L115)

Come back if that's not clear.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/rsconf/pull/183

> Add to [conf.py.jinja](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/package_data/sirepo_jupyterhub/conf.py.jinja)

Done

> Add code [like this](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L111). It could be constructed from the nginx.vhost and assume https.

I don't think nginx.vhost is populated in time. It sets the [vhost here](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/nginx.py#L67). That get's the [vhost from sirepo](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L129) so I used it.

> Add a line [like this one](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L115)

I believe [that is already done](https://github.com/radiasoft/rsconf/blob/ae704a1eb3c4141bfa7620d0b048bb3d5eafd36b/rsconf/component/sirepo.py#L201)

**Comment by robnagler** [comment]
> I don't think nginx.vhost is populated in time. It sets the vhost here. That get's the vhost from sirepo so I used it.

I meant sirepo.vhost. See https://github.com/radiasoft/rsconf/pull/183#discussion_r849994520
