### ISSUE TITLE
v6 should be setup as a bop host

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#186]
Following the development instructions when I run 
```bash
cd ~/v4
radia_run vagrant-rsconf-dev
```
I get an install error. I then tried
```bash
cd v4
vssh
rsc
```

I got the same install error. Turning on `install_debug` I see that it when trying to access `biviosoftware/container-perl/radiasoft-download.sh`. That file doesn't exist on the build server (v3). Cloning the `container-perl` repo on the build server solved the problem. 

This should either
- be part of the development instructions
- be done automatically by the installer on the build server
- container-perl shouldn't be required.

Need to figure out what it is used for...

**Comment by robnagler** [comment]
There's a comment in vagrant-rsconf-dev:

    # For building perl rpms (see build-perl-rpm.sh)

However, the line after seems to be missing.

We need perl for bivio-named.
