### ISSUE TITLE
Add filebeats as a component

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#202]

**Comment by Benbenbenin0** [comment]
**Security Configurations**

(Default) TLS encryption for HTTP API clients/Beats
- Auto-configures TLS for HTTP layer with a generated CA cert ‘http.p12’
- [https://www.elastic.co/guide/en/beats/filebeat/8.2/securing-communication-elasticsearch.html](url)

(Additional) Restrict system calls made by Filebeat to limit kernel exposure using _seccomp_, "Linux Secure Computing Mode"
- [https://www.elastic.co/guide/en/beats/filebeat/8.2/linux-seccomp.html](url)
