### ISSUE TITLE
Add elasticsearch as a component

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#203]

**Comment by Benbenbenin0** [comment]
**Security Configurations**

(Default) Password user authentication for HTTP layer before completing requests/API calls
- Superuser ‘elastic’ is autogenerated on first service startup, password is printed to console
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/change-passwords-native-users.html](url)

(Default) TLS encryption and mutual authentication for internode communication (node enrollment requires Kibana)
- Auto-configures TLS for transport layer with a generated CA cert ‘transport.p12’
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/security-basic-setup.html](url)

(Default) Key enrollment for Elasticsearch nodes
- Temporary keys are generated by Elasticsearch upon request
- [https://www.elastic.co/guide/en/elasticsearch/reference/master/create-enrollment-token.html](url)

(Standard) Isolate Elastic cluster behind a VPN or Firewall to prevent malicious requests
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/es-security-principles.html](url)

(Standard) Run Elasticsearch with a dedicated, unprivileged user to prevent easy root access
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html]

(Standard) Configure 'IP filters’ to allow/block unwanted connections to the cluster
- Manages a list of IP addresses/hosts, subnets and domains
- Can separate lists by http and transport layer
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/ip-filtering.html](url)

(Standard) Change file paths for Elasticsearch data and log storage (defaults to /var)
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html](url)

(Standard)  Roll-based access control with assigned privileges to restrict Elasticsearch functions/data
- Special permissions can be given to defined rolls (ex. ‘read privilege on documents that match query X’)
- Defined rolls can be assigned to groups of users
- Users are stored within ‘Realms’ defined by authentication process, can be configured
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html](url)

(Additional) Configure alternate TLS cipher suites for added encryption
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/ciphers.html](url)

(Additional) Enable security audit feature to track details about failed authentications, refused connections, etc.
- Heavily inclusive with large amounts of event attributes, can implement ignore policies
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/enable-audit-logging.html](url)

(Additional) Implement intermediary application between users and API requests to prevent direct user facing and track user behavior (request type, user, target node, etc.)
- Would make request on behalf of users (ex. funnel search input to query commands)
- [https://www.elastic.co/guide/en/elasticsearch/reference/current/es-security-principles.html](url)
