### ISSUE TITLE
sirepo unmoderated juptyerhublogin does not work

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#209]
Describe issue better. Need testing protocol and fix.

**Comment by e-carlin** [comment]
Cases we need to handle:
- default_proprietary_sim_types using SirepoAuthenticator image
- default_proprietary_sim_types using Authenticator image
- moderated_sim_types using Authenticator image

Authenticator image is "new" and SirepoAuthenticator is "old".
