### ISSUE TITLE
sirepo_sandbox component

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#210]
A sirepo_sandbox is almost like mpi_worker: a docker container that runs sshd for a single user. The purpose is to allow a user to develop sirepo, using ssh to copy files.

Unlike mpi_worker, there need to be multiple instances on the node. This is similar to how bop starts multiple apps. However, these users need different ports to ssh into. 

The network should be isolated so only ssh will work, and everything else is tunneled into and out of the container via ssh. This would allow a user to  connect to the development server on the node from a local browser. We will need to use docker proxy for this.

Files have to persist so there will be read-write volumes mounted, specifically ~/.ssh, ~/src/radiasoft, and ~/jupyter. The latter is used to persist ~/jupyter/pre_jupyter_bashrc and ~/jupyter/bashrc. That's a convenient hook for this problem. No need to invent something new for this problem.

Already encrypted private keys will need to be distributed to end users outside the rsconf configured nodes. This is different than mpi_worker which uses non-encrypted keys and the distribution happens to external devices (laptops). The main point is the key is encrypted by sirepo_sandbox component with a passphrase that is configured and transferred to users along with the keys. The protocol can be manual as it is all happening inside the organization.

**Comment by e-carlin** [comment]
Are we developing inside of docker or is sirepo just running in docker? If we are developing I'd like all of `~/src` to be mounted (ex so I can have ~/src/e-carlin/home-env)

**Comment by robnagler** [comment]
We may consider vagrant+libvirt: https://codingpackets.com/blog/vagrant-libvirt-install-centos-7/ This is working on Ubuntu just fine. It might be easier for people who want to develop in emacs on the server. 

There are some issues with networking, but I think they can be solved with port forwarding instead of a private network.

**Comment by e-carlin** [comment]
We settled on libvirt for now. Going to get a test account up
