### ISSUE TITLE
devbox: kicked out of ssh session on error

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#234]
try `echo 'exit 1' > x.sh && bash x.sh`. You'll be dropped back onto whatever machine you ssh'ed in from

**Comment by robnagler** [comment]
This is from the bashrc that had a set -e. That's should be changed.

**Comment by e-carlin** [comment]
Thanks.

@robnagler I'd like to implement this change but it is causing the devboxs to restart which I'd like to prevent (users can just log in and out when they want to pick up the change). I'm using `rsconf_append` to add lines to the jupyter/bashrc which sets [rsconf_service_file_changed](https://github.com/radiasoft/rsconf/blob/5614ec2c841e976c484121df7f0002f0b2472c6b/rsconf/package_data/rsconf/rsconf.sh#L25). The run_d is a [watched file](https://github.com/radiasoft/rsconf/blob/5614ec2c841e976c484121df7f0002f0b2472c6b/rsconf/systemd.py#L77) and jupyter/bashrc is below that so it [triggers a restart](https://github.com/radiasoft/rsconf/blob/5614ec2c841e976c484121df7f0002f0b2472c6b/rsconf/package_data/rsconf/rsconf.sh#L412). Can you advice how to best prevent the restart from happening? Maybe add a flag to rsconf_append to turn off tracking of the file in rsconf_service_file_changed?

**Comment by robnagler** [comment]
You'd need to exclude a file from restarts. That could be possible. I wouldn't worry about it for now. Just do the restart.

**Comment by robnagler** [comment]
workaround in the mean time:

set +ueo pipefail

**Comment by e-carlin** [comment]
Should I work with Paul to find a good time or just kick him out when I want to restart?

**Comment by robnagler** [comment]
Just restart
