### ISSUE TITLE
devbox: strange sirepo db structure

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#236]
```bash
run$ pwd
/home/vagrant/src/radiasoft/sirepo/run/run/run
```

That is the directory structure that is created after running `sirepo service http` and trying to use sirepo.

**Comment by robnagler** [comment]
I'm not seeing this on my devbox.

**Comment by e-carlin** [comment]
A `pip install -e .` of Sirepo fixed it.
