### ISSUE TITLE
devbox: TERM=xterm-256color in emacs shell should be TERM=dumb

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#240]
I'm not sure what's causing this but it makes a mess of my shell window.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/container-beamsim-jupyter/blob/master/container-conf/build.sh#L174 ?

**Comment by robnagler** [comment]
I think this is something different. That's at the global shell level. zz-10-base.sh should be doing the right thing but it isn't.

**Comment by robnagler** [comment]
done
