### ISSUE TITLE
devbox: error that is preventing ssh access

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#244]
Maybe something with bashrc?
```
~$ ssh devbox
-bash: 0: command not found
-bash: 95: command not found
-bash: 0c#!: command not found
```

**Comment by e-carlin** [comment]
Not sure where this came from but removed.

**Comment by robnagler** [comment]
I'm sorry. This occasional happens in starting up emacs. It's probably clear screen or something. I edited our bashc's manually when updating them last night. Apologies for not noticing.

**Comment by e-carlin** [comment]
No worries!
