### ISSUE TITLE
devbox didn't populate repos

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#245]
We setup a new user, and they didn't get the repos populated. Part of this may be that the repos are private so the code needs to be robust.

**Comment by e-carlin** [comment]
We [only populate home-env](https://github.com/radiasoft/rsconf/blob/b152d9dfbcc26eb4f9e8b690335be2daab6ae247/rsconf/component/devbox.py#L75)

**Comment by robnagler** [comment]
I think we need some type of curl installer for this, possibly using package path for the list of repos.
