### ISSUE TITLE
devbox ~/.ssh is read-only

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#258]
So things like adding known_hosts doesn't work. 

Maybe let the user specify their own config https://stackoverflow.com/a/10765980/5518313

**Comment by e-carlin** [comment]
Not a blocker for me for the moment but a nice to have

**Comment by robnagler** [comment]
Could be a symlink to ~/jupyter/.ssh.

**Comment by robnagler** [comment]
The setup uses that directory for sshd, which is probably wrong. That should be ~/.devbox_sshd or something and mounted read-only. The other directory could be a link to ~/jupyter/.ssh

**Comment by robnagler** [comment]
vm_devbox
