### ISSUE TITLE
devbox needs read-write ~/.ssh to develop sirepo sbatch

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#300]
@e-carlin why does ~/.ssh need to be read-only? I'll work around by updating config manually.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/rsconf/pull/217#discussion_r931512944

I'm not sure of the exact reasoning. But one thought is that sshd_config lives in ~/.ssh. A user could change that file to make the system insecure. That file could live somewhere else read-only.

**Comment by robnagler** [comment]
Makes sense. Since `/srv/devbox_<user>` is mounted read only. Should be easy to split the two. The config for sshd could actually stay and then just modify `cmd` to look in `/srv/devbox_<user>/sshd/sshd_config`. 

We will need to be careful about overwriting files in `/srv/devbox_<user>/ssh`. There would be a one-time drop, and then if the file changed, it wouldn't get updated. If someone hoses their ssh directory, we can simply remove it and have rsconf recreate it.

**Comment by robnagler** [comment]
vm_devbox
