### ISSUE TITLE
vm_devbox: vm left in strange state after `systemctl start ...`

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#439]
`VBoxManage list vms` sees the vm. `VBoxManage list runningvms` and `vagrant status` both report the vm isn't running. But, the ports it opens are still in use and ps reports a process running that I imagine in the process running the vm `/usr/lib/virtualbox/VBoxHeadless --comment vm_devbox_<user>_default_1706914636725_53375 --startvm de13588f-3c97-4004-9e9a-10c41c77a177 --vrde config.

I can't run `vagrant up` manually on the vm because there are port conflicts. `vagrant halt` does nothing. Killing that VBoxHeadless process frees up the ports. 

If I run the start script by hand then the vm is started fine. So, that leads me to believe it is systemd. I wonder if it is cleaning up the processes (some of them...) that start created when the start script exits? I see the KillMode config in the systemd.service docs but it seems only applicable to ExecStop.

**Comment by robnagler** [comment]
https://serverfault.com/a/982333 ?

**Comment by e-carlin** [comment]
No dice. I adapted it to use vagrant instead of vbox cli. Maybe vagrant does something different...

**Comment by e-carlin** [comment]
PrivateTmp was the culprit...

**Comment by e-carlin** [comment]
Fixed by https://github.com/radiasoft/rsconf/pull/441
