### ISSUE TITLE
vm_devbox: systemctl restart leaves vm shutdown

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#448]
Different behaviors for different users. When I restart my vm it is left in a running state. When I restart another users vm it is left in "poweroff" state...

**Comment by e-carlin** [comment]
Switching which vm starts first causes the shutdown behavior to move to the second user started. So, whoever starts second it shut down.

**Comment by e-carlin** [comment]
Switching to Type=oneshot and RemainAfterExit=yes fixes the issue. This has the downside that systemd doesn't monitor the actual vm process. For example, if the vm is powered off outside of systemd (ex it crashes) and you run `systemctl status` it will report the vm still running. This isn't the worst thing in the world. The vms are unlikely to crash. But, it could be confusing for a sysadmin.

The other option I think would be to managed pid files and then tell systemd about them. It's guessing algorithm (or using cgroups) I think is what's getting in the way right now.

**Comment by robnagler** [comment]
pidfile may be tricky to implement.

**Comment by e-carlin** [comment]
Ya, looks like a rabbit hole. oneshot and remainafterexit it is...
