### ISSUE TITLE
/etc/postfix/sender_access not created

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#513]
Running `radia_run vagrant-rsconf-dev` I get this error:
```
curl -L -s -S -n file:///home/vagrant/src/radiasoft/rsconf/run/srv/host/v3.radia.run//etc/postfix/sender_access
curl: (37) Couldn't open file /home/vagrant/src/radiasoft/rsconf/run/srv/host/v3.radia.run//etc/postfix/sender_access
tail: cannot open ‘/root/radia-run-install.log’ for reading: No such file or directory
Unexpected error; Install failed.
```

**Comment by e-carlin** [comment]
@robnagler what's the proper behavior when whitelist_senders is empty? The sender_access file will be empty. And [empty files aren't written](https://github.com/radiasoft/rsconf/blob/b65b70b3d67c918e725d18d13d7b8128d243fc70/rsconf/component/__init__.py#L512). We then try to pull over this empty file that doesn't exist which blows up.

**Comment by robnagler** [comment]
Looks like that line should be: `file_contents is None`

**Comment by e-carlin** [comment]
Thanks
