### ISSUE TITLE
add http config for kickstart

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#534]
No longer serving kickstart files over nfs. Now using http. So, add to http config

```
    location /kickstart/ {
        alias /srv/kickstart/;
    }
```

**Comment by robnagler** [comment]
This probably should be off of <root>/kickstart. There is a question about whether this should be public information. Kickstart should have restricted IPs.

**Comment by e-carlin** [comment]
> off of /kickstart

What does that mean? A subpath of /kickstart (ex /kickstart/foo)?
