### ISSUE TITLE
shmmax defaults to 64mb

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#94]
[Need to pass --shm-size=XXXm](https://stackoverflow.com/a/35884597) in order to increase size. May also need to configure systemd to allow larger shm.

@cchall: @moellep noticed your process maxed out shm on one of your rsmpi jobs. Do you think it is limiting your performance? Depends on how MPI is using shared memory.

**Comment by cchall** [comment]
I didn't think MPI normally used shared memory. I really don't know if it could be limiting performance in some way.

Do you know what sort process it was? I'm running all Warp jobs on rsmpi right now.

**Comment by cchall** [comment]
> I'm pretty sure MPI tries to use shared memory for IPC when it can.

After actually reading up on this, it is definitely the case that MPI defaults to shared memory for communication on a single node. There is even some guidance from the OpenMPI FAQ on this: https://www.open-mpi.org/faq/?category=sm#how-much-use

Seems like it would be good to increase the shared memory allocation some, assuming MPI will use what it is given.

**Comment by robnagler** [comment]
I'll give it 8GB, and we'll see what it uses. There's 64GB on a node.

**Comment by robnagler** [comment]
Fix 7d887ba8fc5397cf9c887f490a424a846426c1b0 and https://github.com/radiasoft/rsdockerspawner/commit/c3c12bb0adcd3b14cfa36df3021bd19b24b23f5f
